#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("a_i_valid", 1, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("a_i_ready", 1, hls_out, 1, "ap_none", "out_data", 1),
	Port_Property("a_i_data", 32, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("a_i_strb", 4, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("b_i_valid", 1, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("b_i_ready", 1, hls_out, 5, "ap_none", "out_data", 1),
	Port_Property("b_i_data", 32, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("b_i_strb", 4, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("c_i_valid", 1, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("c_i_ready", 1, hls_out, 9, "ap_none", "out_data", 1),
	Port_Property("c_i_data", 32, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("c_i_strb", 4, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("d_o_valid", 1, hls_out, 12, "ap_none", "out_data", 1),
	Port_Property("d_o_ready", 1, hls_in, 13, "ap_none", "in_data", 1),
	Port_Property("d_o_data", 32, hls_out, 14, "ap_none", "out_data", 1),
	Port_Property("d_o_strb", 4, hls_out, 15, "ap_none", "out_data", 1),
	Port_Property("clear", 1, hls_in, 16, "ap_none", "in_data", 1),
	Port_Property("enable", 1, hls_in, 17, "ap_none", "in_data", 1),
	Port_Property("function_r", 1, hls_in, 18, "ap_none", "in_data", 1),
	Port_Property("start_r", 1, hls_in, 19, "ap_none", "in_data", 1),
	Port_Property("shift", 5, hls_in, 20, "ap_none", "in_data", 1),
	Port_Property("len", 11, hls_in, 21, "ap_none", "in_data", 1),
	Port_Property("f_cnt", 11, hls_out, 22, "ap_vld", "out_data", 1),
	Port_Property("f_cnt_ap_vld", 1, hls_out, 22, "ap_vld", "out_vld", 1),
	Port_Property("f_valid", 1, hls_out, 23, "ap_vld", "out_data", 1),
	Port_Property("f_valid_ap_vld", 1, hls_out, 23, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "cont";
